---
title: "Probability Theory"
author: "Wisam Alsaba"
format: 
    html:
      code-line-numbers: true
      df-print: paged
---
----
#### **Assignment 1.1**
```{r}


# Define the probabilities and complementary probabilities
# the dash refers to the complementary probability
P_S <- 0.3
P_T_S <- 0.2
P_T_S_dash <- 0.6
P_S_dash <- 1 - P_S
P_T_dash_S <- 1 - P_T_S
P_T_dash_S_dash <- 1 - P_T_S_dash

# Calculate the conditional probabilities
# inter refers to intersection
P_T_inter_S <- P_S * P_T_S
P_T_inter_S_dash <- P_S_dash * P_T_S_dash
P_T_dash_inter_S <- P_S * P_T_dash_S
P_T_dash_inter_S_dash <- P_S_dash * P_T_dash_S_dash

# Execute the results
print(P_T_inter_S)
print(P_T_inter_S_dash)
print(P_T_dash_inter_S)
print(P_T_dash_inter_S_dash)
```
#### **Assignment 1.2**
```{r}
# Load all necessary libraries
library(tidyverse)
library(ggVennDiagram)

# Total Number of observations
num_observations <- 1000

# Create tibble to simulate user device usage
user_devices <- tibble(
  user_id = 1:num_observations,
  smartphone = rbinom(num_observations, 1, 0.4),
  tablet = ifelse(smartphone == 1, rbinom(num_observations, 1, 0.2), rbinom(num_observations, 1, 0.5)),
  computer = ifelse(tablet == 1, rbinom(num_observations, 1, 0.1), rbinom(num_observations, 1, 0.3))
)

# Ensure at least one device is active for each user
user_devices <- user_devices %>%
  rowwise() %>% 
  mutate(smartphone = ifelse(sum(smartphone, tablet, computer) == 0, 1, smartphone))

# Display the first ten lines
head(user_devices, 10)

# Get column sums
column_sums <- colSums(user_devices)

# Extract sets for each device
users_with_smartphone <- which(user_devices$smartphone == 1)
users_with_tablet <- which(user_devices$tablet == 1)
users_with_computer <- which(user_devices$computer == 1)

# List of all device sets
device_sets <- list(users_with_smartphone, users_with_tablet, users_with_computer)

# Plot Venn diagram to visualize device usage overlap
ggVennDiagram(device_sets, category.names = c("Smartphone", "Tablet", "Computer"),
              label_percent_digit = 2) +
  # Customize appearance
  theme(legend.position = "none", 
        panel.background = element_rect("white"),
        strip.background = element_rect("white")) +
  scale_x_continuous(expand = expansion(mult = .24))

# Calculate intersection of all three device sets
users_with_all_devices <- Reduce(intersect, device_sets)
percentage_all_devices <- length(users_with_all_devices) / num_observations * 100
cat("Percentage of customers using all three devices:", round(percentage_all_devices, 2), "%\n")

# Calculate union of sets for users with at least two devices
users_with_at_least_two <- union(intersect(users_with_smartphone, users_with_tablet), union(intersect(users_with_smartphone, users_with_computer), 
                                       intersect(users_with_computer, users_with_tablet)))
percentage_at_least_two_devices <- length(users_with_at_least_two) / num_observations * 100
cat("Percentage of customers using at least two devices:", round(percentage_at_least_two_devices, 2), "%\n")

# Calculate sets for users using only one device independently
users_with_only_smartphone <- users_with_smartphone[!(users_with_smartphone %in% users_with_tablet) & 
                                                      !(users_with_smartphone %in% users_with_computer)]
users_with_only_tablet <- users_with_tablet[!(users_with_tablet %in% users_with_smartphone) & 
                                              !(users_with_tablet %in% users_with_computer)]
users_with_only_computer <- users_with_computer[!(users_with_computer %in% users_with_smartphone) & 
                                                  !(users_with_computer %in% users_with_tablet)]
percentage_only_one_device <- (length(users_with_only_smartphone) + length(users_with_only_tablet) + 
                                 length(users_with_only_computer)) / num_observations * 100
cat("Percentage of customers using just one device:", round(percentage_only_one_device, 2), "%\n")
```
#### **Assignment 1.3**
```{r}
#Calculating the probabilities
Prob_A <- 0.04
Prob_B_A <- 0.97
Prob_B_A_Dash <- 0.01
Prob_A_Dash <- 1- Prob_A
Prob_B_Dash_A <- 1 - Prob_B_A
Prob_B_Dash_A_Dash <- 1 - Prob_B_A_Dash
Prob_B <- (Prob_B_A*Prob_A)+(Prob_B_A_Dash*Prob_A_Dash)
Prob_A_Dash_given_B <- (Prob_B_A_Dash * Prob_A_Dash)/Prob_B
Prob_A_given_B <- (Prob_B_A * Prob_A)/Prob_B
#print the probabilities
print(Prob_A_Dash_given_B)
print(Prob_A_given_B)
```